version: '3.9'
services:
  backend:
    container_name: petstore_backend
    build:
      context: ./petstore_backend
    ports:
      - 8080:8080
    volumes:
    - ./petstore_backend:/opt/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      RAILS_ENV: test
    command: bash -c "rm -f /opt/app/tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
  db:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - db_pg13:/var/lib/postgresql/data
volumes:
  db_pg13:          
